/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 playstation2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/playstation2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[1.927, 0, -3.697]} rotation={[-Math.PI / 2, 0, 0]} scale={1.958}>
        <group position={[0.843, 0.502, 0]}>
          <mesh geometry={nodes.Object_7.geometry} material={materials['DeathtrapDungeon.001']} position={[-1.189, -0.13, 0.685]} rotation={[-Math.PI / 2, 0, 0]} />
        </group>
      </group>
      <group scale={0.01}>
        <mesh geometry={nodes.MainBody_LP_1_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.lightindicator.geometry} material={materials.phong1} />
        <mesh geometry={nodes.MainBody_LP_2_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.powerbutton.geometry} material={materials.phong1} />
        <mesh geometry={nodes.MainBody_LP_3_phong1_0.geometry} material={materials.phong1} position={[1.655, 0, 0]} />
        <mesh geometry={nodes.MainBody_LP_4_phong1_0.geometry} material={materials.phong1} />
        <mesh geometry={nodes.MainBody_LP_5_phong1_0.geometry} material={materials.phong1} />
      </group>
    </group>
  )
}

useGLTF.preload('/playstation2.glb')
