/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 omnitrix.glb 
*/

import React, { useRef } from 'react'
import { useFrame } from 'react-three-fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { NodeToyMaterial } from '@nodetoy/react-nodetoy';
import {data as domData} from "./shaderData"
import {data as screenData} from "./screenshader"


export function Omnitrix(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/omnitrix.glb')
  const { actions } = useAnimations(animations, group)

  useFrame(() => {
    // Use the Sine helper function to create an oscillating motion
    group.current.position.y =  Math.sin((performance.now() / 2000)) *0.5
  });
  return (
    <group position={[-15,-5.2,2]} rotation={[0,2,.2]} scale={1}>
       <mesh castShadow  position={[0,0.5,0]}  rotation={[1,2,0]}>
       <sphereGeometry args={[2.2, 100, 100]} /> {/* Use sphereGeometry */}
        <NodeToyMaterial  data={domData} />
      </mesh>
    <group ref={group} {...props} dispose={null} scale={0.6} >
      <group name="Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Circle001_8" position={[0, 1.894, -0.001]} scale={[1.001, 0.897, 1.01]} />
              <group name="Circle002_9" position={[0, 2.906, -0.001]} scale={[0.939, 0.981, 0.947]} />
              <group name="Circle003_10" position={[0, 3.054, 0.845]} rotation={[0.829, 0, 0]} scale={[0.125, 0.13, 0.127]} />
              <group name="Circle004_12" position={[-0.863, 3.054, 0]} rotation={[Math.PI / 2, -0.742, 1.571]} scale={[0.125, 0.13, 0.127]} />
              <group name="Circle005_14" position={[0.852, 3.052, -0.02]} rotation={[-1.573, -0.6, 1.567]} scale={[-0.125, -0.13, -0.127]} />
              <group name="Circle006_16" position={[-0.045, 3.054, -0.852]} rotation={[2.312, 0, -3.142]} scale={[0.125, 0.13, 0.127]} />
              <group name="Plane002_19" position={[0.391, 2.961, -0.301]} rotation={[0, -0.598, 0]} scale={[0.042, 0.339, 0.339]} />
              <group name="Plane003_20" position={[-0.34, 2.985, -0.292]} rotation={[-Math.PI, -0.572, 0]} scale={[-0.042, -0.339, -0.339]} />
              <group name="Sphere002_15" position={[0.888, 3.072, -0.02]} rotation={[-1.595, -1.43, 1.546]} scale={0.113} />
              <group name="Sphere003_17" position={[-0.045, 3.079, -0.885]} rotation={[-Math.PI, 0, -Math.PI]} scale={-0.113} />
              <group name="Sphere004_18" position={[0, 1.91, 1.328]} rotation={[0.819, 0, 0]} scale={0.195} />
              <group name="Sphere_11" position={[0, 3.079, 0.878]} scale={-0.113} />
              <group name="Mball020_22" position={[0.554, 1.067, 1.957]} rotation={[0, -0.951, 0]} scale={0.168} />
              <group name="Plane_7" position={[0, -0.165, -0.009]} scale={[1.807, 1.117, 1.088]}>
                <group name="BezierCurve001_3" position={[-0.14, 0, 0]} rotation={[-Math.PI, 0, 0]} scale={[-0.597, -1, -1]} />
                <group name="BezierCurve_2" position={[0.154, 0, 0]} scale={[0.597, 1, 1]}>
                  <group name="Object_6_1">
                    <mesh castShadow name="Object_1" geometry={nodes.Object_1.geometry} 
                    // material={materials['Material.006']} 
                    >
                                          <meshToonMaterial color={0xffffff}/>

                    </mesh>
                    <mesh castShadow name="Object_1_1" geometry={nodes.Object_1_1.geometry} ><meshBasicMaterial color={0x000000}/></mesh>
                  </group>
                  <group name="Object_6001" position={[0.781, 0.94, -0.068]} rotation={[Math.PI, 0, Math.PI]}>
                    {/* <mesh castShadow name="Object_1001" geometry={nodes.Object_1001.geometry} 
                    // material={materials['Material.006']} 
                    /> */}
<mesh castShadow name="Object_1001" geometry={nodes.Object_1001.geometry}                    // material={materials['Material.006']} 
                    >
                                          <meshToonMaterial color={0xffffff}/>

                    </mesh>
                    <mesh castShadow name="Object_1001_1" geometry={nodes.Object_1001_1.geometry} ><meshBasicMaterial color={0x000000}/></mesh>
                  </group>
                </group>
                <group name="Circle007_5" position={[0, 1.858, 1.228]} rotation={[0.788, 0, 0]} scale={[0.126, 0.093, 0.208]}>
                  <group name="Object_12" position={[0.058, 0.828, 0.032]}>
                    <mesh castShadow name="Object_4_1" geometry={nodes.Object_4_1.geometry} >
                                    <meshToonMaterial color={0x414141}/></mesh>
                    <mesh castShadow name="Object_4_2" geometry={nodes.Object_4_2.geometry} ><meshBasicMaterial color={0x000000}/></mesh>
                  </group>
                </group>
                <group name="Circle_4" position={[0, 2.052, 0.008]} scale={[0.628, 0.644, 1.052]}>
                  <group name="Object_10_1" position={[0, 0.07, 0]}>
                    <mesh castShadow name="Object_3" geometry={nodes.Object_3.geometry} 
                    // material={materials['Material.009']} 
                    >
        <meshToonMaterial color={0x121212}/>

                    </mesh>
                    <mesh castShadow name="Object_3_1" geometry={nodes.Object_3_1.geometry} ><meshBasicMaterial color={0x000000}/></mesh>
                  </group>
                </group>
                <group name="Plane001_6" position={[0, 1.942, 0]} scale={[0.538, 0.891, 0.921]}>
                  <group name="Object_14">
                    <mesh castShadow name="Object_5" geometry={nodes.Object_5.geometry} 
                    // material={materials['Material.008']}
                     >
                       <meshToonMaterial color={0x121212}/>

                     </mesh>
                    <mesh castShadow name="Object_5_1" geometry={nodes.Object_5_1.geometry} ><meshBasicMaterial color={0x000000}/></mesh>
                  </group>
                </group>
                <group name="Object_4">
                  <mesh castShadow name="Object_0" geometry={nodes.Object_0.geometry} 
                  // material={materials['Material.003']}
                   >
                    <meshToonMaterial color={0x414141}/>
                   </mesh>
                  <mesh castShadow name="Object_0_1" geometry={nodes.Object_0_1.geometry} ><meshBasicMaterial color={0x000000}/></mesh>
                  
                </group>
              </group>
            </group>
          </group>
        </group>
        <group name="Axis,cylinder,screen" position={[-0.009, 2.461, 0.002]}>
          <mesh castShadow name="cylinder" geometry={nodes.cylinder.geometry} material={materials['Material.001']} position={[0.02, -0.442, -0.001]} scale={[1.001, 0.897, 1.01]} />
          <mesh castShadow name="cylinderlights" geometry={nodes.cylinderlights.geometry} material={materials['Material.007']} position={[0.031, -0.477, 0.02]} scale={[1.001, 0.897, 1.01]} />
          <mesh castShadow name="screen" geometry={nodes.screen.geometry} 
          // material={materials['Material.002']} 
          position={[0.009, -1.105, -0.003]} scale={[1.001, 0.897, 1.01]} >
                                <meshToonMaterial color={0x56BE54}/>
                                {/* <NodeToyMaterial  data={screenData} /> */}


          </mesh>
        </group>
        <group name="Axis,rotation" position={[-0.009, 2.461, 0.002]}>
          <mesh castShadow name="Object_21" geometry={nodes.Object_21.geometry} 
          // material={materials['Material.010']} 
          position={[0.009, -0.093, -0.003]} scale={[0.939, 0.981, 0.947]} >
                    <meshToonMaterial color={0x121212}/>

            </mesh>
          <group name="Rim" position={[0.009, -0.093, -0.003]} scale={[0.939, 0.981, 0.947]}>
            <mesh castShadow name="Object_9" geometry={nodes.Object_9.geometry} 
            // material={materials['Material.009']} 
            >
                      <meshToonMaterial color={0x414141}/>

            </mesh>
            <mesh castShadow name="Object_9_1" geometry={nodes.Object_9_1.geometry} ><meshBasicMaterial color={0x000000}/></mesh>
          </group>
          <group name="RimBulbs1" position={[0.01, 0.095, -0.002]} rotation={[0.829, 0, 0]} scale={[0.129, 0.134, 0.13]}>
            <mesh castShadow name="Object_11" geometry={nodes.Object_11.geometry} 
            // material={materials['Material.004']} 
            >
                                    <meshToonMaterial color={0x414141}/>

            </mesh>
            <mesh castShadow name="Object_11_1" geometry={nodes.Object_11_1.geometry} ><meshBasicMaterial color={0x000000}/></mesh>
            <mesh castShadow name="Object_11_2" geometry={nodes.Object_11_2.geometry} 
            material={materials['Material.014']} >
                                              <meshToonMaterial color={0x56BE54}/>

            </mesh>
          </group>
          <group name="RimBulbs2" position={[0.01, 0.095, -0.002]} rotation={[1.58, 0.741, -1.578]} scale={[0.132, 0.13, 0.13]}>
            <mesh castShadow name="Object_11002" geometry={nodes.Object_11002.geometry} >
                                    <meshToonMaterial color={0x414141}/>

            </mesh>
            <mesh castShadow name="Object_11002_1" geometry={nodes.Object_11002_1.geometry} ><meshBasicMaterial color={0x000000}/></mesh>
            <mesh castShadow name="Object_11002_2" geometry={nodes.Object_11002_2.geometry}  >
                                              <meshToonMaterial color={0x56BE54}/>

            </mesh>
          </group>
        </group>
        <mesh castShadow name="Object_41" geometry={nodes.Object_41.geometry} 
        material={materials['Material.011']} 
        position={[0.391, 2.438, -0.301]} rotation={[0, -0.598, 0]} scale={[0.042, 0.339, 0.339]} >
          
        </mesh>
        <mesh castShadow name="Object_42" geometry={nodes.Object_42.geometry} 
        // material={materials['Material.004']} 
        position={[0.35, 2.438, -0.344]} rotation={[0, -0.598, 0]} scale={[0.046, 0.388, 0.351]} >
        <meshToonMaterial color={0x717171}/>

        </mesh>
        <mesh castShadow name="Object_44" geometry={nodes.Object_44.geometry} 
        material={materials['Material.011']} position={[-0.384, 2.461, -0.292]} 
        rotation={[-Math.PI, -0.572, 0]} scale={[-0.042, -0.339, -0.339]} />
        <group name="Sphere001" position={[0.021, 1.967, 1.387]} scale={0.162}>
          <mesh castShadow name="Sphere001_1" geometry={nodes.Sphere001_1.geometry} >
                                              <meshToonMaterial color={0x56BE54}/>

            </mesh>
          <mesh castShadow name="Sphere001_2" geometry={nodes.Sphere001_2.geometry} ><meshBasicMaterial color={0x000000}/></mesh>
        </group>
      </group>
    </group>
    </group>
  )
}

useGLTF.preload('/omnitrix.glb')
